const Data = [
  {
    id: "2",
    name: "Book Morty Smith",
    status: "nuevo",
    precio: 343,
    genero: "hombre",
    image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
  },
  {
    id: "3",
    name: "Summer Smith",
    status: "nuevo",
    precio: 2343,
    genero: "hombre",
    image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
  },
  {
    id: "4",
    name: "Book Beth Smith",
    status: "usado",
    precio: 243,
    genero: "hombre",
    image: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
  },
  {
    id: "23",
    name: "Book historia",
    status: "nuevo",
    precio: 2243,
    genero: "hombre",
    image: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
  },
  {
    id: "323",
    name: "Book historia",
    status: "mujer",
    precio: 3000,
    genero: "mujer",
    image: "https://rickandmortyapi.com/api/character/avatar/37.jpeg",
  },
  {
    id: "3623",
    name: "Book del Arte ",
    status: "nuevo",
    precio: 100,
    genero: "mujer",
    image: "https://rickandmortyapi.com/api/character/avatar/39.jpeg",
  },
  {
    id: "23",
    name: "Book maritima",
    status: "nuevo",
    precio: 23,
    genero: "mujer",
    image: "https://rickandmortyapi.com/api/character/avatar/431.jpeg",
  },
  {
    id: "323",
    name: "Book gelatina",
    status: "nuevo",
    precio: 23,
    genero: "mujer",
    image: "https://rickandmortyapi.com/api/character/avatar/41.jpeg",
  },
];

export default Data;
